version: "3.9"

services:
  frontend:
    image: nginx
    volumes:
     - nginx_logs:/logs
     - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./frontend/www:/www:ro
     # - ./keys/ssl-dev/:/ssl:ro
    ports:
     - "80:80"
     - "443:443"
    command: [nginx]

  angr:
    build:
      context: backend/angr

  binja:
    build:
      context: backend/binja

  ghidra:
    build:
      context: backend/ghidra

  ida:
    build:
      context: backend/ida

volumes:
  nginx_logs:
